### ISSUE TITLE
make book failed with error message sh: fruby: command not found

### ISSUE THREAD

**Issue by housekeeponline** [bcrowell/purcell#3]
Please help!
After make all_figures succeeds,
make book failed with error message sh: fruby: command not found on MacOS10.12
How can I install fruby (I've not found it online.
Thank you for your help!

**Comment by bcrowell** [comment]
The fruby script is included in the repository. Make sure it's executable and that you have ruby installed.

**Comment by housekeeponline** [comment]
Thanks a lot! purcell.pdf was made but it had no figure at all. Below shows error messages
make all_figures
# The following requires Inkscape 0.47 or later.
perl -e 'foreach my $f(<ch*/figs/*.svg>) {system("scripts/render_one_figure.pl $f")}'
rendering figure ch01/figs/assembling-three-charges.svg
  INKSCAPE_PORTABLE_PROFILE_DIR=/tmp/pDNGiZY52q inkscape --export-text-to-path --export-pdf=ch01/figs/assembling-three-charges.pdf ch01/figs/assembling-three-charges.svg  --export-area-drawing 1>/dev/null
preflight_one_fig.pl, svg file ch01/figs/assembling-three-charges.svg, bad structure for ch01/figs/assembling-three-charges.pdf detected by qpdf --check:

  preflight failed on pdf rendering of ch01/figs/assembling-three-charges.svg , probably due to transparency; rendering to bitmap instead
error deleting z-1.ppm, No such file or directory at scripts/render_one_figure.pl line 106.
rendering figure ch01/figs/crystal-pe.svg
  INKSCAPE_PORTABLE_PROFILE_DIR=/tmp/sW4yCkQkYr inkscape --export-text-to-path --export-pdf=ch01/figs/crystal-pe.pdf ch01/figs/crystal-pe.svg  --export-area-drawing 1>/dev/null
preflight_one_fig.pl, svg file ch01/figs/crystal-pe.svg, bad structure for ch01/figs/crystal-pe.pdf detected by qpdf --check:
